### ISSUE TITLE
Wrong SHA256 for wcstools blocks installation

### ISSUE THREAD

**Issue by gmorain** [larrybradley/homebrew-astro#2]
Hi, I had to ```brew edit wcstool``` and replace the SHA256 value with `525f6970eb818f822db75c1526b3122b1af078affa572dce303de37df5c7b088` for the installation to proceed

**Comment by larrybradley** [comment]
@gmorain Thanks for reporting this. I've updated the SHA256. 

At some point `wcstools` started distributing a different version of the `wcstools-3.9.7.tar.gz` file (which IMHO is not great behavior).  I have a copy of the original `wcstools-3.9.7.tar.gz` file that matches the old SHA256.

**Comment by gmorain** [comment]
You are welcome. This is what I imagined, and I also think this is quite inappropriate (to replace the file without a new version without renaming it). Thank you for the quick fix!
